//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ivanov_WPF_EF_Employees
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentsEmployees
    {
        public int de_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
